name : Mock Deploy Pipeline (Test)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
    mock-build:
      runs-on: ubuntu-latest
      outputs:
        images: ${{steps.build.outputs.image}}
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Mock - Configure AWS credentials
          run: echo "aws-configuration Test"

        - name: Mock - Login to Docker
          run: echo "Docker login"

        - name: Mock - Build Docker image
          run : echo "Docker build"

        - name: Mock - Push image to ECR
          id : build
          run : echo "Docker push"

          